@echo off
setlocal DisableDelayedExpansion
set "AI_AGENT_SOURCE=%~dp0"
set "AI_AGENT_LAUNCHER=%~f0"
set "PSModulePath=%SystemRoot%\System32\WindowsPowerShell\v1.0\Modules"
"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NonInteractive -ExecutionPolicy Bypass -STA -Command "$ErrorActionPreference='Stop'; $locked=@(); try { $source=$env:AI_AGENT_SOURCE; $app=Join-Path $source 'App.ps1'; if (-not (Test-Path -LiteralPath $app -PathType Leaf)) { if (Test-Path -LiteralPath $source -PathType Container) { throw 'Source App.ps1 is missing. Check the shared release.' }; $local=Join-Path $env:LOCALAPPDATA 'AiPromptsAgent'; $p=Get-Content -LiteralPath (Join-Path $local 'app\current.json') -Raw -Encoding UTF8 | ConvertFrom-Json; if ($p.release -cnotmatch '^[0-9]+\.[0-9]+\.[0-9]+-[a-f0-9]{64}$' -or $p.app_sha256 -cnotmatch '^[a-f0-9]{64}$') { throw 'Invalid local release metadata.' }; $app=Join-Path $local ('app\'+$p.release+'\App.ps1'); if ((Get-FileHash -LiteralPath $app -Algorithm SHA256).Hash.ToLowerInvariant() -cne $p.app_sha256) { throw 'Local release integrity check failed.' } }; $set=[IO.Path]::GetDirectoryName($app); foreach($n in @('App.ps1','index.html',[IO.Path]::GetFileName($env:AI_AGENT_LAUNCHER))){$locked+=[IO.File]::Open((Join-Path $set $n),[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read)}; $raw=(New-Object Text.UTF8Encoding($false,$true)).GetString([IO.File]::ReadAllBytes($app)); $m=[regex]::Matches($raw,'(?m)^# Release-Binding: ([A-Za-z0-9+/=]+)\r?$'); if($m.Count -ne 1){throw 'INVALID_RELEASE: Missing sealed release binding.'}; $b=ConvertFrom-Json ((New-Object Text.UTF8Encoding($false,$true)).GetString([Convert]::FromBase64String($m[0].Groups[1].Value))); if($b.schema_version -ne 1 -or $b.release_id -cnotmatch '^[a-f0-9]{32}$' -or $b.channel -cnotin @('development','candidate','production') -or $b.state_contract -notin @(1,2)){throw 'INVALID_RELEASE: Unsupported binding.'}; $normalized=[regex]::Replace($raw,'(?m)^# Release-Binding: [^\r\n]*','# Release-Binding: NORMALIZED'); $sha=[Security.Cryptography.SHA256]::Create(); try{$actual=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($normalized)))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}; $set=[IO.Path]::GetDirectoryName($app); if($actual -cne $b.app_payload_sha256 -or (Get-FileHash -LiteralPath (Join-Path $set 'index.html') -Algorithm SHA256).Hash.ToLowerInvariant() -cne $b.html_sha256 -or (Get-FileHash -LiteralPath (Join-Path $set ([IO.Path]::GetFileName($env:AI_AGENT_LAUNCHER))) -Algorithm SHA256).Hash.ToLowerInvariant() -cne $b.cmd_sha256){throw 'INVALID_RELEASE: Mixed or changed App/HTML/CMD; launch refused.'}; & $app -Mode Bootstrap -SourcePath $source; if (-not $?) { exit 1 } } catch { Write-Host ([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('6LW35YuV44OV44Kh44Kk44Or44KS56K66KqN44Gn44GN44G+44Gb44KT44Gn44GX44Gf44CC6YWN5biD5ouF5b2T6ICF44Gr44CB5ZCM44GY54mI44GuM+ODleOCoeOCpOODq+OBqOOCouOCr+OCu+OCueaoqemZkOOCkueiuuiqjeOBl+OBpuOCguOCieOBo+OBpuOBj+OBoOOBleOBhOOAgg=='))); Write-Host $_.Exception.Message; exit 1 } finally { foreach($h in $locked){$h.Dispose()} }"
set "AI_AGENT_EXIT=%ERRORLEVEL%"
if not "%AI_AGENT_EXIT%"=="0" pause
endlocal & exit /b %AI_AGENT_EXIT%
